### ISSUE TITLE
Missing timestamp content in utils.py?

### ISSUE THREAD

**Issue by iRuizeWu** [KegangWangCCNU/PhysBench#1]
In dump_datatape there should be a store for the timestamp.

**Comment by iRuizeWu** [comment]
I still run into some problems. Shouldn't we use `eval_on_dataset` when testing? It will show that the timestamp, path attributes are missing. So, the tests should be rewritten themselves. My dataset is pure.

**Comment by KegangWangCCNU** [comment]
Please make sure you are passing in a dataset file, not a datatape file. Dataset files can be used to generate datatape and for testing, while datatape is only used for training. If your issue is still not resolved, please show your code so I can further identify the problem. Additionally, I recommend reading our tutorial 

https://github.com/KegangWangCCNU/PhysBench/blob/main/Tutorial/Noob%20Heart.ipynb

 to understand how it works.

**Comment by iRuizeWu** [comment]
Oh! Thanks ! I mistakenly used datatape.
